version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: "monthly"
      time: "00:00"
    # Add assignees
    assignees:
      - "Cubik65536"
    # Add reviewers
    reviewers:
      - "Cubik65536"
    commit-message:
      prefix: 'build'
      prefix-development: 'build'
      include: 'scope'
    # Specify labels for GitHub Actions pull requests
    labels:
      - "type:ci"
      - "type:dependencies"
      - "prio:high"
    open-pull-requests-limit: 25
